### ISSUE TITLE
Initial tasks

### ISSUE THREAD

**Issue by yuokada** [y-leisures/golden-image#13]
## Tasks

- [x] Add systemd service and configurations for DB backup
- [x] Add fluentd configuration to send nginx logs to the s3 bucket
- [x] Add `ExecStartPre` directive to bms.service to log in aws-ecr
